import Link from "next/link";
import { notFound } from "next/navigation";
import { getReportBySlug } from "@/lib/reports";

export const dynamic = "force-dynamic";

export default async function SharedReportPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const report = await getReportBySlug(slug);
  if (!report) notFound();

  return (
    <main className="shell">
      <nav className="topbar" aria-label="Main navigation">
        <div className="brand">
          <span>AdoptCheck</span>
        </div>
        <div className="top-actions">
          <span>Shared report</span>
          <Link className="quiet-link" href="/">
            Scan a repo &rarr;
          </Link>
        </div>
      </nav>

      <section className="report" aria-label={`Due diligence report for ${report.repo.fullName}`}>
        <div className="verdict-band">
          <div>
            <p className="verdict-kicker">Verdict for {report.repo.fullName}</p>
            <h2 className="verdict-title">
              <span className={`verdict-${report.verdict.toLowerCase()}`}>{report.verdict}</span>
              <span className="verdict-pill">{report.confidence} confidence</span>
            </h2>
            <p className="bottom-line">{report.bottomLine}</p>
          </div>
          <div className="report-actions">
            <a className="secondary-button" href={report.repo.htmlUrl} target="_blank" rel="noreferrer">
              Open repo
            </a>
          </div>
        </div>

        <div className="grid">
          <div className="section">
            <h2>Scores</h2>
            <ul className="score-list">
              {report.scores.map((score) => (
                <li className="score-row" key={score.category}>
                  <span className="score-name">{score.name}</span>
                  <span className="score-label">
                    {score.label} · {score.score}/100
                  </span>
                  <span className="meter" aria-hidden="true">
                    <span style={{ width: `${score.score}%` }} />
                  </span>
                </li>
              ))}
            </ul>
          </div>

          <div className="section">
            <h2>Top Risks</h2>
            <ul className="risk-list">
              {(report.risks.length ? report.risks : ["No major blocker appeared in the deterministic scan."]).map(
                (risk) => (
                  <li key={risk}>{risk}</li>
                )
              )}
            </ul>
          </div>
        </div>

        {report.llmAnalysis.status === "generated" && (
          <div className="section ai-section">
            <div className="section-title-row">
              <h2>AI Analyst</h2>
            </div>
            <div className="analysis-body">
              <p>{report.llmAnalysis.summary}</p>
              <dl className="analysis-list">
                <div>
                  <dt>README Honesty</dt>
                  <dd>{report.llmAnalysis.readmeHonesty}</dd>
                </div>
                <div>
                  <dt>Next Action</dt>
                  <dd>{report.llmAnalysis.nextAction}</dd>
                </div>
              </dl>
            </div>
          </div>
        )}

        <div className="section">
          <h2>Repo Signals</h2>
          <ul className="meta-list">
            <li>{report.repo.stars.toLocaleString()} stars</li>
            <li>{report.repo.forks.toLocaleString()} forks</li>
            <li>{report.repo.openIssues.toLocaleString()} open issues</li>
            <li>{report.repo.license ? report.repo.license.name : "No detected license"}</li>
          </ul>
        </div>
      </section>

      <p className="footer-note">
        Generated by <Link className="quiet-link" href="/">AdoptCheck</Link> — open-source repo due diligence. This shared
        report reflects the scan at the time it was run.
      </p>
    </main>
  );
}
